version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Porte-noire123
      - OPENSEARCH_SECURITY_DISABLED=false
      - OPENSEARCH_SECURITY_ALLOW_DEFAULT_INIT_SECURITYINDEX=true
      - OPENSEARCH_SECURITY_ADMIN_PASSWORD=admin1234
      - OPENSEARCH_SECURITY_READONLY_USER_PASSWORD=user1234
    ports:
      - "9200:9200"
      - "9600:9600"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    depends_on:
      - opensearch

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.9.2
  #   container_name: logstash
  #   # volumes:
  #     # - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #   ports:
  #     - "5044:5044"
  #   depends_on:
  #     - opensearch
